# Configuration for auto-assign action
# https://github.com/kentaro-m/auto-assign-action

# Issues configuration
issues:
  # Users to automatically assign to new issues
  assignees:
    - MAVERICK-VF142

# Pull requests configuration
pull_requests:
  # Users to automatically assign as reviewers to new PRs
  reviewers:
    - MAVERICK-VF142
  # Users to automatically assign to new PRs
  assignees:
    - MAVERICK-VF142

# Optional: Add a comment when auto-assigning
add_reviewers: true
add_assignees: true