# Configuration file for the labeler action
# https://github.com/actions/labeler

# Documentation changes
documentation:
  - "*.md"
  - "docs/**"
  - "LICENSE"
  - "*.rst"
  - "*.txt"

# Bug-related files
bug:
  - "test.py"
  - "test/**"
  - "**/test*"
  - "**/*test*"

# Feature/enhancement files
feature:
  - "app.py"
  - "**/*.py"
  - "templates/**"
  - "static/**"

# Configuration files
config:
  - "requirements.txt"
  - "vercel.json"
  - "*.json"
  - "*.yml"
  - "*.yaml"
  - "*.toml"
  - "*.ini"
  - "*.cfg"

# CI/CD related files
ci:
  - ".github/**"
  - "*.yml"
  - "*.yaml"
  - ".gitignore"
  - ".gitattributes"

# Frontend related files
frontend:
  - "templates/**"
  - "static/**"
  - "**/*.html"
  - "**/*.css"
  - "**/*.js"

# Backend/Python related files
backend:
  - "**/*.py"
  - "requirements.txt"

# Dependencies
dependencies:
  - "requirements.txt"
  - "setup.py"
  - "pyproject.toml"