name: "Welcome"

on:
  issues:
    types: [opened]

permissions:
  contents: read
  issues: write

jobs:
  welcome:
    runs-on: ubuntu-latest
    steps:
    - name: Welcome first-time contributors
      uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: |
          👋 Welcome to **Drx.MediMate**! 
          
          Thanks for opening your first issue! We're excited to have you as part of our community. 
          
          🦖 **Aditi** is your AI-powered pharmaceutical assistant, and we appreciate your contribution to making healthcare information more accessible.
          
          Please make sure to:
          - Provide clear and detailed information about the issue
          - Include steps to reproduce if it's a bug
          - Follow our contributing guidelines in the README
          
          A maintainer will review your issue soon. Thank you for helping us improve! 🚀
